/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GradSchoolRole;

import Business.EcoSystem;
import Business.Citizen.Citizen;
import Business.Citizen.CitizensDirectory;
import Business.Email.SendMail;
import Business.WorkQueue.GradSchoolRequest;
import Business.WorkQueue.VocationalTrainingRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manis
 */
public class ProcessGradReqJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessGradReqJPanel
     */
    JPanel userProcessContainer;
    GradSchoolRequest request;
    CitizensDirectory cd;
    EcoSystem business;

    ProcessGradReqJPanel(JPanel userProcessContainer, GradSchoolRequest request, CitizensDirectory cd, EcoSystem business) {
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.cd = cd;
        this.business = business;
        

        initComponents();
        populateData();

    }

    void populateData() {
        txtHeader.setText("Review Applicant: " + request.getSender().getUsername());

        ArrayList<Business.Citizen.Citizen> citDir = business.getCd().getCitizens_Dir();
        
        
        System.out.println(citDir);

        for (Citizen v : citDir) {
            System.out.println(v);
            if (v.getUsername().equals(request.getSender().getUsername())) {
                txtCitizenID.setText("Citizen ID: " + v.getCitizen_ID());
                txtAddress.setText("Address: " + v.getResidentAddress());
                txtGender.setText("Gender: " + v.getGender());
                txtEmail.setText("Email Address: " + v.getEmail());
                break;

            }
        }

        txtHS.setText(request.getHighSchool());
        txtHS1.setText(request.getHighschoolGrade());
        txtHS2.setText(request.getBachelorUniv());
        txtHS3.setText(request.getBachelorGrade());
        txtHS4.setText(request.getBachelorDegree());
        txtHS5.setText(request.getDesUniv());
        txtHS6.setText(request.getDesProgram());
        txtHS7.setText(request.getDesIntake());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHeader = new javax.swing.JLabel();
        txtCitizenID = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtAddress = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtHS = new javax.swing.JLabel();
        txtHS1 = new javax.swing.JLabel();
        txtHS2 = new javax.swing.JLabel();
        txtHS3 = new javax.swing.JLabel();
        txtHS4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHS5 = new javax.swing.JLabel();
        txtHS6 = new javax.swing.JLabel();
        txtHS7 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        rejectJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHeader.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHeader.setFocusable(false);
        add(txtHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 357, 32));

        txtCitizenID.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtCitizenID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtCitizenID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 210, 25));

        txtGender.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 210, 25));

        txtEmail.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 210, 25));

        txtAddress.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 210, 25));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 100, 40));

        txtHS.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtHS.setForeground(new java.awt.Color(204, 204, 204));
        txtHS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 210, 25));

        txtHS1.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtHS1.setForeground(new java.awt.Color(204, 204, 204));
        txtHS1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtHS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 210, 25));

        txtHS2.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtHS2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtHS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 210, 25));

        txtHS3.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtHS3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtHS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 210, 25));

        txtHS4.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtHS4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtHS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 210, 25));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel1.setText("Applicant Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 150, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel2.setText("Seeking Admission for:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, 20));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel3.setText("Bachelor's Degree Information");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 240, -1));

        txtHS5.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtHS5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtHS5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 210, 25));

        txtHS6.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtHS6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtHS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 210, 25));

        txtHS7.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        txtHS7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtHS7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 210, 25));

        submitJButton.setBackground(new java.awt.Color(102, 102, 102));
        submitJButton.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        submitJButton.setText("Accept");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, 120, 40));

        rejectJButton.setBackground(new java.awt.Color(102, 102, 102));
        rejectJButton.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        rejectJButton.setText("Reject");
        rejectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJButtonActionPerformed(evt);
            }
        });
        add(rejectJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 100, 40));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel4.setText("High School Information");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 200, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Graduation Request Process Admin Portal");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 380, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin3.jpeg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        GradSchoolWorkAreaJPanel dwjp = (GradSchoolWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        request.setStatus("Accepted");
        JOptionPane.showMessageDialog(null, "Candidate: " + request.getSender().getUsername() + " Accepted. Status will be updated accordingly.", "Information", JOptionPane.INFORMATION_MESSAGE);
        submitJButton.setEnabled(false);
        rejectJButton.setEnabled(false);

        String to = "pravindhuri1295@gmail.com";
        String subject = "Update regarding your application";
        String user = "yoursmartcityportal@gmail.com";
        String pass = "Pass@123";
        String message = " Hello, " + "\n\n"
                + "Thank you for applying at " + txtHS5.getText() + ". We are happy to inform you that your application has been Accepted."
                + "Best of luck for your future"
                + "\n\n "
                + "Regards " + "\n\n"
                + txtHS5.getText();

        SendMail.send(to, subject, message, user, pass);
        


    }//GEN-LAST:event_submitJButtonActionPerformed

    private void rejectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJButtonActionPerformed
        // TODO add your handling code here:
        request.setStatus("Rejected");
        JOptionPane.showMessageDialog(null, "Candidate: " + request.getSender().getUsername() + " has been Rejected. Status will be updated accordingly.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        rejectJButton.setEnabled(false);
        submitJButton.setEnabled(false);
        
        String to = "pravindhuri1295@gmail.com";
        String subject = "Update regarding your application";
        String user = "yoursmartcityportal@gmail.com";
        String pass = "Pass@123";
        String message = " Hello " + "\n\n"
                + "Thank you for applying at " + txtHS5.getText() + ". We regret to tell you that your application has been rejected."
                + "Best of luck for your future"
                + "\n\n "
                + "Regards " + "\n\n"
                + txtHS5.getText();

        SendMail.send(to, subject, message, user, pass);

    }//GEN-LAST:event_rejectJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton rejectJButton;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtCitizenID;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtHS;
    private javax.swing.JLabel txtHS1;
    private javax.swing.JLabel txtHS2;
    private javax.swing.JLabel txtHS3;
    private javax.swing.JLabel txtHS4;
    private javax.swing.JLabel txtHS5;
    private javax.swing.JLabel txtHS6;
    private javax.swing.JLabel txtHS7;
    private javax.swing.JLabel txtHeader;
    // End of variables declaration//GEN-END:variables
}
