/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Citizen.Citizen;
import javax.swing.table.DefaultTableModel;
import Business.Citizen.CitizensDirectory;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author pravin
 */
public class ManageCitizens extends javax.swing.JPanel {
   private JPanel processContainer;
    private EcoSystem system;
    CitizensDirectory cit_Dir;
    /**
     * Creates new form ViewAllVeterans
     */
    public ManageCitizens(JPanel userProcessContainer, EcoSystem system,CitizensDirectory cit_Dir) {
        initComponents();
        this.cit_Dir = cit_Dir;
        this.processContainer = userProcessContainer;
        this.system = system;
        populateCitizensDetails();
    }
 public void populateCitizensDetails() {
        int rowCount = tblViewAllCitizen.getRowCount();
        DefaultTableModel model = (DefaultTableModel) tblViewAllCitizen.getModel();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        for (Citizen v : system.getCd().getCitizens_Dir()) {
            Object row[] = new Object[6];
            row[0] = v;
            row[1] = v.getCitizen_ID();
            row[2] = v.getAge();
            row[3] = v.getGender();
            row[4] = v.getEmail();

            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewAllCitizen = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonDelete = new javax.swing.JToggleButton();
        txtCitName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblViewAllCitizen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Citizen Name ", "Citizen ID", "Age", "Gender", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewAllCitizen);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 820, 185));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("View Citizens");
        jLabel6.setFocusable(false);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 140, 30));

        buttonDelete.setText("Delete Citizen");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 140, -1));
        add(txtCitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 210, 30));

        jLabel1.setText("Enter Citizen Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 306, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

     
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        processContainer.remove(this);
        Component[] componentArray = processContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) processContainer.getLayout();
        layout.previous(processContainer);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        
//       DefaultTableModel model = (DefaultTableModel) tblViewAllCitizen.getModel();
//
//       
//
//       try{
//       int SelectedRowIndex = tblViewAllCitizen.getSelectedRow();
//       model.removeRow(SelectedRowIndex);
//       }catch(Exception ex)
//       {
//           JOptionPane.showMessageDialog(null, "Please select the row !", "Warning", JOptionPane.WARNING_MESSAGE);
//       }
       
        DefaultTableModel model = (DefaultTableModel) tblViewAllCitizen.getModel();

        String citizenName = txtCitName.getText();
        ArrayList<Citizen> citizenList = system.getCd().getCitizens_Dir();
        for(int i=0;i<citizenList.size();i++){
            if(citizenList.get(i).getFirstName().equals(citizenName)){
                citizenList.remove(i);
                break;
            }
            
        }
        
      
        txtCitName.setText("");
        JOptionPane.showMessageDialog(null, "Citizen Deleted Successfully !");
 
    }//GEN-LAST:event_buttonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewAllCitizen;
    private javax.swing.JTextField txtCitName;
    // End of variables declaration//GEN-END:variables
}
