/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VocSchoolRole;

import Business.EcoSystem;
import Business.Email.SendMail;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.JobOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.Citizen;
import Business.UserAccount.UserAccount;
import Business.Citizen.Citizen;
import Business.Citizen.CitizensDirectory;
import Business.WorkQueue.JobWorkRequest;
import Business.WorkQueue.VocationalTrainingRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pravin
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    JPanel userProcessContainer;
    VocationalTrainingRequest request;
    CitizensDirectory cd;
    EcoSystem system;
    UserAccount account;

    ProcessWorkRequestJPanel(JPanel userProcessContainer, VocationalTrainingRequest request, CitizensDirectory cd,EcoSystem system,UserAccount account) {

        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.cd = cd;
        this.system = system;
        this.account = account;

        initComponents();
        txtHeader.setText("Review Applicant: " + request.getSender().getUsername());


        ArrayList<Business.Citizen.Citizen> citDir = system.getCd().getCitizens_Dir();

        for (Citizen v : citDir) {
            if (v.getUsername().equals(request.getSender().getUsername())) {
                txtCitD.setText("Citizen ID: " + v.getCitizen_ID());
                txtAddress.setText("Address: " + v.getResidentAddress());
                txtGender.setText("Gender: " + v.getGender());
                txtEmail.setText("Email Address: " + v.getEmail());
                break;

            }
        }

        txtCampus.setText("Campus: " + request.getCampus());
        txtQual.setText("Highest Qualification: " + request.getHighestQualification());
        txtCourse.setText("Course: " + request.getAreaofInterest());
        txtFunding.setText("Funding Required?: " + request.getFundingRequired());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rejectJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        txtCourse = new javax.swing.JLabel();
        txtHeader = new javax.swing.JLabel();
        txtCampus = new javax.swing.JLabel();
        txtFunding = new javax.swing.JLabel();
        txtQual = new javax.swing.JLabel();
        txtCitD = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtAddress = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();
        btnRecommendForJob = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rejectJButton.setBackground(new java.awt.Color(102, 102, 102));
        rejectJButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        rejectJButton.setForeground(new java.awt.Color(255, 255, 255));
        rejectJButton.setText("Reject");
        rejectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJButtonActionPerformed(evt);
            }
        });
        add(rejectJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 170, 30));

        submitJButton.setBackground(new java.awt.Color(102, 102, 102));
        submitJButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Accept");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 170, 30));

        backJButton.setBackground(new java.awt.Color(102, 102, 102));
        backJButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 553, 80, 30));

        txtCourse.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        txtCourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 250, 25));

        txtHeader.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtHeader.setFocusable(false);
        add(txtHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 357, 32));

        txtCampus.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        txtCampus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 250, 25));

        txtFunding.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        txtFunding.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtFunding, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 250, 25));

        txtQual.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        txtQual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtQual, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 250, 25));

        txtCitD.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        txtCitD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtCitD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 250, 25));

        txtGender.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        txtGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 250, 25));

        txtEmail.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 250, 25));

        txtAddress.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 250, 25));

        btnComplete.setBackground(new java.awt.Color(102, 102, 102));
        btnComplete.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnComplete.setForeground(new java.awt.Color(255, 255, 255));
        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 170, 30));

        btnRecommendForJob.setBackground(new java.awt.Color(102, 102, 102));
        btnRecommendForJob.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnRecommendForJob.setForeground(new java.awt.Color(255, 255, 255));
        btnRecommendForJob.setText("Recommend For Job");
        btnRecommendForJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecommendForJobActionPerformed(evt);
            }
        });
        add(btnRecommendForJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 170, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View and Process Vocational Course Request - Admin Access");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 760, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin3.jpeg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void rejectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJButtonActionPerformed
        // TODO add your handling code here:
        request.setStatus("Rejected");
        JOptionPane.showMessageDialog(null, "Candidate: " + request.getSender().getUsername() + " Rejected. Status will be updated accordingly.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        rejectJButton.setEnabled(false);
        submitJButton.setEnabled(false);

        String message = "User: " + request.getSender().getUsername() + "'s Application for " + request.getAreaofInterest()+ " at " + request.getCampus() + " was rejected by Admin: " + request.getReceiver().getUsername();


    }//GEN-LAST:event_rejectJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        request.setStatus("Accepted");
        JOptionPane.showMessageDialog(null, "Candidate: " + request.getSender().getUsername() + " Accepted. Status will be updated accordingly.", "Information", JOptionPane.INFORMATION_MESSAGE);
        submitJButton.setEnabled(false);
        rejectJButton.setEnabled(false);
        //btnComplete.setEnabled(false);

        String message = "User: " + request.getSender().getUsername() + "'s Application for " + request.getAreaofInterest()+ " Training at " + request.getCampus() + " was Accepted by Admin: " + request.getReceiver().getUsername();


    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VocationalSchoolAreaJPanel dwjp = (VocationalSchoolAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
    
        
    private void btnRecommendForJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecommendForJobActionPerformed
        // TODO add your handling code here:
      if(request.getStatus()=="Graduated")
      {

        JobWorkRequest jrequest = new JobWorkRequest();
        jrequest.setAreaofInterest(txtCourse.getText());
        jrequest.setCampus(txtCampus.getText());
        jrequest.setHighestQualification(txtQual.getText());
        jrequest.setCandidateName(request.getSender().getUsername());
        Organization org = null;

        for (Network network : system.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                //                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                //Step 3:check against each organization for each enterprise
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof JobOrganization) {
                        org = organization;
                        break;
                    }
                }
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(jrequest);
            System.out.println("Added Request to Organization ");
            account.getWorkQueue().getWorkRequestList().add(jrequest);
            System.out.println("Added Request to UserAccount ");
            
            String to = "pravindhuri1295@gmail.com";
            String subject = "Request for Citizens job";
            String user = "yoursmartcityportal@gmail.com";
            String pass = "Pass@123";
            JOptionPane.showMessageDialog(null, "Candidate: " + request.getSender().getUsername() + "Job Recommendation Sent to Admin!", "Information", JOptionPane.INFORMATION_MESSAGE);
            btnRecommendForJob.setEnabled(false);
        

            //SendMail.send(to,subject, message, user, pass);
        }
        
    }//GEN-LAST:event_btnRecommendForJobActionPerformed
    }
    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        if(request.getStatus()=="Accepted")
        {
            request.setStatus("Graduated");
            JOptionPane.showMessageDialog(null, "Candidate: " + request.getSender().getUsername() + " Graduated. Status will be updated accordingly.", "Warning", JOptionPane.INFORMATION_MESSAGE);
            rejectJButton.setEnabled(false);
            submitJButton.setEnabled(false);
            btnComplete.setEnabled(false);

    }//GEN-LAST:event_btnCompleteActionPerformed
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnRecommendForJob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton rejectJButton;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtCampus;
    private javax.swing.JLabel txtCitD;
    private javax.swing.JLabel txtCourse;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFunding;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtHeader;
    private javax.swing.JLabel txtQual;
    // End of variables declaration//GEN-END:variables
}
