/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PermanentHousing;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Listings.HouseListings;
import Business.Listings.HouseListingDirectory;
import Business.Organization.Organization;
import Business.Organization.PermHousingOrganization;
import Business.UserAccount.UserAccount;
import Business.Citizen.CitizensDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manis
 */
public class AddListingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddListingJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private final PermHousingOrganization permHousingOrganization;
    private CitizensDirectory cd;
    private Enterprise enterprise;
    HouseListingDirectory hsd ;
    
    public AddListingJPanel(JPanel userProcessContainer, UserAccount account, Organization permHousingOrganization, Enterprise enterprise, CitizensDirectory cd,EcoSystem business) 
 {
        initComponents();
        //hsd = new HouseListingDirectory();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.permHousingOrganization = (PermHousingOrganization) permHousingOrganization;
        this.enterprise = enterprise;
        this.cd = cd;
 }
   public HouseListingDirectory getDir() {
        return hsd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStreetName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDoorNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPinCode = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Area : ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 25));

        txtArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 150, 25));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Street Name : ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 25));

        txtStreetName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 150, 25));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Door Number : ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 25));

        txtDoorNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDoorNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoorNumberActionPerformed(evt);
            }
        });
        add(txtDoorNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 150, 25));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("City : ");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, 25));

        txtCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 150, 25));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Pin Code : ");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 150, 25));

        txtPinCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtPinCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 150, 25));

        btnAdd.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnAdd.setText("Add Listing");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 110, 40));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Admin Portal for Adding Houses for Sale");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 430, 40));

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 90, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/houses.jpeg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(txtArea.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please add an Area");
             return;
         }
        if(txtCity.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please add a city");
             return;
         }
        if(txtStreetName.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please add a street name");
             return;
         }
        if(txtDoorNumber.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please add an Apartment Number");
             return;
         }
        if(txtPinCode.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please add a PinCode");
             return;
         }
        if(txtPinCode.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please enter number of people");
             return;
         }
        try{
                      if(!txtPinCode.getText().equals(""))
         Integer.parseInt(txtPinCode.getText());
         }
         catch(NumberFormatException ex){
          JOptionPane.showMessageDialog(null,"  Pincode cannot be string");
           return;
         }
        
         try{
                      if(!txtDoorNumber.getText().equals(""))
         Integer.parseInt(txtDoorNumber.getText());
         }
         catch(NumberFormatException ex){
          JOptionPane.showMessageDialog(null,"  Apartment number cannot be string");
           return;
         }
        HouseListings houseListing = business.getHld().addHouseListing();
        houseListing.setArea(txtArea.getText());
        houseListing.setCity(txtCity.getText());
        houseListing.setStName(txtStreetName.getText());
        houseListing.setAptNo(txtDoorNumber.getText());
        houseListing.setPinCode(txtPinCode.getText());
        txtArea.setText("");
        txtCity.setText("");
        txtStreetName.setText("");
        txtDoorNumber.setText("");
        txtPinCode.setText("");
        JOptionPane.showMessageDialog(null, "Listing has been added. Citizens can view it.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtDoorNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoorNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoorNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDoorNumber;
    private javax.swing.JTextField txtPinCode;
    private javax.swing.JTextField txtStreetName;
    // End of variables declaration//GEN-END:variables
}
