/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TemporaryHousing;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Listings.TempHouseListing;
import Business.Organization.Organization;
import Business.Organization.PermHousingOrganization;
import Business.Organization.TempHousingOrganization;
import Business.UserAccount.UserAccount;
import Business.Citizen.CitizensDirectory;
import Business.WorkQueue.PermHousingRequest;
import Business.WorkQueue.TempHousingRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.ViewAllCitizens;

/**
 *
 * @author pravin
 */
public class TempHousingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TempHousingWorkAreaJPanel
     */
    private JPanel processContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization tempHousingOrganization;
    private CitizensDirectory cd;
    private Enterprise enterprise;
   
    

    public TempHousingWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization tempHousingOrganization, Enterprise enterprise, CitizensDirectory cd,EcoSystem business) {
        initComponents();
        this.processContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.tempHousingOrganization = (TempHousingOrganization) tempHousingOrganization;
        this.enterprise = enterprise;
        this.cd = cd;
        populateTempTable();
        
        txtAvlHouses.setText(Integer.toString(CalculateAvailableHouses()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAvlHouses = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        addtemphousingjButton = new javax.swing.JButton();
        txtWelcome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotalRequests = new javax.swing.JLabel();
        txtAccepted = new javax.swing.JLabel();
        txtRejected = new javax.swing.JLabel();
        txtPending = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTotalRequests1 = new javax.swing.JLabel();
        txtAccepted1 = new javax.swing.JLabel();
        txtRejected1 = new javax.swing.JLabel();
        txtPending1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnViewAllVeterans = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Temporary Housing Work Area");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 500, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Available Houses:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 420, 130, 26));

        txtAvlHouses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAvlHouses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvlHousesActionPerformed(evt);
            }
        });
        add(txtAvlHouses, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 310, 25));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Housing Society Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 730, 96));

        assignJButton.setBackground(new java.awt.Color(102, 102, 102));
        assignJButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        assignJButton.setForeground(new java.awt.Color(255, 255, 255));
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 200, 30));

        processJButton.setBackground(new java.awt.Color(102, 102, 102));
        processJButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        processJButton.setForeground(new java.awt.Color(255, 255, 255));
        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 180, 30));

        addtemphousingjButton.setBackground(new java.awt.Color(102, 102, 102));
        addtemphousingjButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        addtemphousingjButton.setForeground(new java.awt.Color(255, 255, 255));
        addtemphousingjButton.setText("Add Temporary Housing Listing ");
        addtemphousingjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtemphousingjButtonActionPerformed(evt);
            }
        });
        add(addtemphousingjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 280, 30));

        txtWelcome.setBackground(new java.awt.Color(51, 51, 51));
        txtWelcome.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtWelcome.setFocusable(false);
        txtWelcome.setOpaque(true);
        add(txtWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 780, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Overall - Across Organization");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setFocusable(false);
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 330, 30));

        txtTotalRequests.setBackground(new java.awt.Color(0, 0, 0));
        txtTotalRequests.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtTotalRequests.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalRequests.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotalRequests.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTotalRequests.setFocusable(false);
        txtTotalRequests.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtTotalRequests.setOpaque(true);
        add(txtTotalRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 75, 40));

        txtAccepted.setBackground(new java.awt.Color(0, 0, 0));
        txtAccepted.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtAccepted.setForeground(new java.awt.Color(255, 255, 255));
        txtAccepted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAccepted.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAccepted.setFocusable(false);
        txtAccepted.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtAccepted.setOpaque(true);
        add(txtAccepted, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 75, 40));

        txtRejected.setBackground(new java.awt.Color(0, 0, 0));
        txtRejected.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtRejected.setForeground(new java.awt.Color(255, 255, 255));
        txtRejected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRejected.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtRejected.setFocusable(false);
        txtRejected.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtRejected.setOpaque(true);
        add(txtRejected, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 75, 40));

        txtPending.setBackground(new java.awt.Color(0, 0, 0));
        txtPending.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPending.setForeground(new java.awt.Color(255, 255, 255));
        txtPending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPending.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPending.setFocusable(false);
        txtPending.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtPending.setOpaque(true);
        add(txtPending, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 75, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Requests");
        jLabel3.setFocusable(false);
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 120, 20));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total Accepted");
        jLabel5.setFocusable(false);
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 120, 20));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Rejected");
        jLabel6.setFocusable(false);
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 110, 20));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total Pending");
        jLabel11.setFocusable(false);
        jLabel11.setOpaque(true);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 110, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("My Requests");
        jLabel10.setFocusable(false);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        txtTotalRequests1.setBackground(new java.awt.Color(0, 0, 0));
        txtTotalRequests1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtTotalRequests1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotalRequests1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTotalRequests1.setFocusable(false);
        txtTotalRequests1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtTotalRequests1.setOpaque(true);
        add(txtTotalRequests1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 75, 40));

        txtAccepted1.setBackground(new java.awt.Color(0, 0, 0));
        txtAccepted1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtAccepted1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAccepted1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAccepted1.setFocusable(false);
        txtAccepted1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtAccepted1.setOpaque(true);
        add(txtAccepted1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 75, 40));

        txtRejected1.setBackground(new java.awt.Color(0, 0, 0));
        txtRejected1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtRejected1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRejected1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtRejected1.setFocusable(false);
        txtRejected1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtRejected1.setOpaque(true);
        add(txtRejected1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 75, 40));

        txtPending1.setBackground(new java.awt.Color(0, 0, 0));
        txtPending1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPending1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPending1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPending1.setFocusable(false);
        txtPending1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtPending1.setOpaque(true);
        add(txtPending1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 75, 40));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total Requests");
        jLabel9.setFocusable(false);
        jLabel9.setOpaque(true);
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 120, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total Accepted");
        jLabel8.setFocusable(false);
        jLabel8.setOpaque(true);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 120, 20));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total Rejected");
        jLabel7.setFocusable(false);
        jLabel7.setOpaque(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 110, 20));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Total Pending");
        jLabel12.setFocusable(false);
        jLabel12.setOpaque(true);
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 110, 20));

        btnViewAllVeterans.setBackground(new java.awt.Color(102, 102, 102));
        btnViewAllVeterans.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnViewAllVeterans.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllVeterans.setText("View Citizens");
        btnViewAllVeterans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllVeteransActionPerformed(evt);
            }
        });
        add(btnViewAllVeterans, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, 150, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/house2.jpeg"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 4, 1000, 650));
    }// </editor-fold>//GEN-END:initComponents

    public int CalculateAvailableHouses()
    {
        int Taken=0;
        int available = 0 ;
        for (WorkRequest request : tempHousingOrganization.getWorkQueue().getWorkRequestList())
        {
            if (request instanceof TempHousingRequest)
            {
                Taken += ((TempHousingRequest) request).getNumberOfPeople();
            }
        }
        for (TempHouseListing th : business.getThld().getTempHouseListing_Dir()) 
        {
              available += th.getNoOfPeople();
        }
     return available-Taken;
        
    }
    public void populateTempTable()
    {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        int totalRequests = 0;
        int acceptedRequests = 0;
        int rejectedRequests = 0;
        int pendingRequests = 0;
        int totalRequestsUser = 0;
        int acceptedRequestsUser = 0;
        int rejectedRequestsUser = 0;
        int pendingRequestsUser = 0;
        int unassignedRequests = 0;
        System.out.println("Inside PopulateTable");

        for (WorkRequest request : tempHousingOrganization.getWorkQueue().getWorkRequestList()) {
            System.out.println("Inside LOOP");
            if (request instanceof TempHousingRequest)
            {
                
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getSender();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getEmployeeName();
            row[3] = request.getStatus();
            row[4] = ((TempHousingRequest) request).getHousingSociety();
            if (request.getReceiver() == null) {
                    unassignedRequests = unassignedRequests + 1;
                } else if (request.getReceiver().getEmployee().equals(userAccount.getEmployee())) {
                    totalRequestsUser = totalRequestsUser + 1;
                    if (request.getStatus().equals("Accepted")) {
                        acceptedRequestsUser = acceptedRequestsUser + 1;
                    } else if (request.getStatus().equals("Rejected")) {
                        rejectedRequestsUser = rejectedRequestsUser + 1;
                    } else {
                        pendingRequestsUser = pendingRequestsUser + 1;
                    }

                }

                if (request.getStatus().equals("Accepted")) {
                    acceptedRequests = acceptedRequests + 1;
                } else if (request.getStatus().equals("Rejected")) {
                    rejectedRequests = rejectedRequests + 1;
                } else {
                    pendingRequests = pendingRequests + 1;
                }
            
            model.addRow(row);
            txtTotalRequests.setText(Integer.toString(totalRequests));
            txtAccepted.setText(Integer.toString(acceptedRequests));
            txtRejected.setText(Integer.toString(rejectedRequests));
            txtPending.setText(Integer.toString(pendingRequests));

            txtTotalRequests1.setText(Integer.toString(totalRequestsUser));
            txtAccepted1.setText(Integer.toString(acceptedRequestsUser));
            txtRejected1.setText(Integer.toString(rejectedRequestsUser));
            txtPending1.setText(Integer.toString(pendingRequestsUser));

            txtWelcome.setText("Welcome back, " + userAccount.getEmployee().getEmployeeName() + "! There are " + (Integer.toString(unassignedRequests)) + " unassigned request(s) for review & " + (Integer.toString(pendingRequests)) + " in your queue.");

        
                
            }
    }
    }
    
    private void txtAvlHousesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvlHousesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvlHousesActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateTempTable();
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        TempHousingRequest request = (TempHousingRequest) workRequestJTable.getValueAt(selectedRow, 0);

        request.setStatus("Processing");

        ProcessTempWorkRequestJPanel processWorkRequestJPanel = new ProcessTempWorkRequestJPanel(processContainer, request);
        processContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) processContainer.getLayout();
        layout.next(processContainer);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void addtemphousingjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtemphousingjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) processContainer.getLayout();
        processContainer.add("AddTempListingJPanel", new AddTempListingJPanel(processContainer, userAccount,tempHousingOrganization,enterprise, cd, business));
        layout.next(processContainer);
    }//GEN-LAST:event_addtemphousingjButtonActionPerformed

    private void btnViewAllVeteransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllVeteransActionPerformed
        // TODO add your handling code here:
        ViewAllCitizens vc = new ViewAllCitizens(processContainer, business, cd);
        processContainer.add("ViewAllCitizens", vc);
        CardLayout layout = (CardLayout) processContainer.getLayout();
        layout.next(processContainer);
    }//GEN-LAST:event_btnViewAllVeteransActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtemphousingjButton;
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton btnViewAllVeterans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processJButton;
    private javax.swing.JLabel txtAccepted;
    private javax.swing.JLabel txtAccepted1;
    private javax.swing.JTextField txtAvlHouses;
    private javax.swing.JLabel txtPending;
    private javax.swing.JLabel txtPending1;
    private javax.swing.JLabel txtRejected;
    private javax.swing.JLabel txtRejected1;
    private javax.swing.JLabel txtTotalRequests;
    private javax.swing.JLabel txtTotalRequests1;
    private javax.swing.JLabel txtWelcome;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
